-- Corriger l'affichage des transactions (app + board)
--
-- NE PAS REJOUER ce fichier : get_user_transactions(uuid) et get_all_transactions() sans
-- arguments sont des failles CRITIQUE #6 et #11 de l'audit (ouvertes à anon, sans aucune
-- vérification). Les versions à jour vivent désormais dans
-- refund-request-response-and-promo.sql (app) et
-- supabase-rpc-get-all-transactions-pagination.sql (board).
